apiVersion: v1
kind: Pod
metadata:
  name: deneme2
spec:
  containers:
  - name: dnm2
    image: ozgurozturknet/k8s
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: application
            operator: In
            values:
            - red
      - weight: 2
        preference:
          matchExpressions:
          - key: app
            operator: In
            values:
            - green
---
