apiVersion: v1
kind: PersistentVolume
metadata:
   name: deneme
   labels:
     app: deneme
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /
    server: 10.255.255.10
