apiVersion: apps/v1
kind: Deployment
metadata:
  name: denemeroll
  labels:
    team: developer
spec:
  replicas: 12
  selector:
    matchLabels:
      app: rolling
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 3
      maxSurge: 3
  template:
    metadata:
      labels:
        app: rolling
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
