apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    name: myapp
spec:
  containers:
  - name: web
    image: nginx
  - name: db
    image: postgres
    env:
      - name: POSTGRES_PASSWORD
        value: password
