apiVersion: v1
kind: Service
metadata:
  name: ornekservice #service ismi
spec:
  type: ClusterIP #tipi
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    team: yazilimci # hangi podla eşleşeceğinin belirlenmesi için label tanımı
