apiVersion: v1
kind: Pod
metadata:
  name: tmp
  labels:
    name: web
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command:
      - sh 
      - -c
      - "tail -f /dev/null"
